### ISSUE TITLE
你好，这些js都在这个网站上，你单独提交上来干

### ISSUE THREAD

**Issue by ScOrPiOzzy** [therehello/therehello.github.io#1]
[https://cdn.jsdelivr.net/gh/00feng00/Cnblogs-Theme-BNDong@7230170d646de3ac13f94af7a4f27a51d1d246cb/js](https://cdn.jsdelivr.net/gh/00feng00/Cnblogs-Theme-BNDong@7230170d646de3ac13f94af7a4f27a51d1d246cb/js)

**Comment by therehello** [comment]
???
